name: Continuous Integration Workflow
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      release_archieve_file:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true
jobs:
  Reusable_CI_Workflow:
    runs-on: [self-hosted]
    steps:
      - name: Import Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
            url: https://vault-internal.dkdevops.online:8200
            token: ${{ secrets.vault_token }}
            tlsSkipVerify: true
            secrets: |
              jfrog/data/artifactory artifactory_user | artifactory_user ;
              jfrog/data/artifactory artifactory_password | artifactory_password ;

      - name: Git checkout
        uses: actions/checkout@v4

      - run: npm install
        name: Install NodeJS modules
        if: ${{ inputs.npm_install }}

      - name: Create version file
        run: echo ${GITHUB_REF_NAME} >VERSION

      - name: Prepare artifact
        run: zip -r artifact.zip ${{inputs.release_archieve_file}}

      - name: Upload artifact
        run: curl -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @artifact.zip -X PUT "http://artifactory-internal.dkdevops.online:8081/artifactory/${{ inputs.project_name }}/${GITHUB_REF_NAME}.zip"

      - name: |
          echo '{
          "environment_variables": [
            {
              "name": "APP_VERSION",
              "secure": false,
              "value": "app_version"
            }
          ],
          "update_materials_before_scheduling": true
          }' | sed -e "s/app_version/${GITHUB_REF_NAME}/" | jq >data.json
          curl 'http://gocd-server.dkdevops.online:8153/go/api/pipelines/${{ inputs.project_name }}/schedule' -H 'Accept: application/vnd.go.cd.v1+json' -H 'Content-Type: application/json' -X POST -d "@data.json"