name: Continuous Integration Workflow
on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  Reusable_CI_Workflow:
    runs-on: [self-hosted]
    steps:
      - name: Import Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
            url: https://vault-internal.dkdevops.online:8200
            token: ${{ secrets.vault_token }}
            tlsSkipVerify: true
            secrets: |
              github/data/sonar sonar_login | sonar_login ;
              github/data/sonar sonar_password | sonar_password ;

      - name: Install dependency
        run: echo "npm install"

      - name: Code Build
        run: echo "Build is successful"

      - name: Code test
        run:  echo "Unit test and Integration test is successful"

      - name: Code review
        run : echo "/opt/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.dkdevops.online:9000 -Dsonar.login=${{ steps.vault-secrets.outputs.sonar_login }} -Dsonar.password=${{ steps.vault-secrets.outputs.sonar_password }} -Dsonar.projectKey=${{ inputs.project-key }}"

      - name: Code release
        run: echo "Code release is successful"


